services:
  app:
    container_name: devops_project1_app
    image: devops-project-1-app
    build:
      context: .
      dockerfile: Dockerfile.production
    command: npm test
    depends_on:
      - db

  db:
    container_name: devops_project1_postgres
    image: postgres:11
    environment:
      POSTGRES_USER: ${NODOS_DB_USERNAME}
      POSTGRES_PASSWORD: ${NODOS_DB_PASSWORD}
