services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.production
    command: npm test
    depends_on:
      - db

  db:
    image: postgres:11
    environment:
      POSTGRES_USER: ${NODOS_DB_USERNAME}
      POSTGRES_PASSWORD: ${NODOS_DB_PASSWORD}
