services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    command: ["nodos", "server", "-h", "0.0.0.0"]

  caddy:
    container_name: devops_project1_caddy
    image: caddy:alpine
    volumes:
      - ./services/caddy/Caddyfile:/etc/caddy/Caddyfile
    ports:
      - 80:80
      - 443:443
    depends_on:
      - app