services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.production
    command: npm test
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: trust